/* Explicit UI catalogue. Partner names and server evidence are never rewritten. */
const messages = {
  onboardingTitle: ["Начните с данных", "Деректерден бастаңыз", "Start with your data"], onboardingHelp: ["Получите заказы по поставщикам с объяснением каждой позиции. Откройте демо или загрузите продажи, остатки и поставки в пути.", "Әр позицияның түсіндірмесі бар жеткізуші тапсырыстарын алыңыз. Демоны ашыңыз немесе сатылымдарды, қалдықтарды және жолдағы жеткізілімдерді жүктеңіз.", "Get supplier orders with an explanation for every item. Open the demo or upload sales, stock and inbound deliveries."], onboardingNote: ["JSON · CSV · XLSX · ZIP. Данные остаются на вашем компьютере. Заказы не отправляются автоматически.", "JSON · CSV · XLSX · ZIP. Деректер компьютеріңізде қалады. Тапсырыстар автоматты түрде жіберілмейді.", "JSON · CSV · XLSX · ZIP. Data stays on your computer. Orders are never sent automatically."],
  staleCalculation: ["Исходные параметры изменились во время расчёта. Выполните новый расчёт перед утверждением.", "Есептеу кезінде бастапқы параметрлер өзгерді. Бекітуден бұрын қайта есептеңіз.", "Inputs changed while calculating. Run a new calculation before approval."], daysShort: ["дн.", "күн", "days"],
  calculationDetails: ["Коэффициенты, округление и календарь поступлений", "Коэффициенттер, дөңгелектеу және түсім күнтізбесі", "Coefficients, rounding and receipt schedule"],
  skip: ["Пропустить", "Өткізу", "Skip"], introHint: ["Открываем рабочее место. Расчёт начнётся по вашей команде.", "Жұмыс орны ашылуда. Есептеу сіздің пәрменіңізбен басталады.", "Opening your workspace. Calculations start when you choose."],
  resetEdits: ["Сбросить правки", "Түзетулерді қалпына келтіру", "Reset edits"], editsPending: ["Изменённых позиций — {count}. Утвердите их, чтобы включить в экспорт.", "Өзгертілген позициялар — {count}. Экспортқа қосу үшін бекітіңіз.", "{count} edited items. Approve changes to include them in exports."], editsReset: ["Ручные правки сброшены. Восстановлены расчётные рекомендации.", "Қолмен енгізілген түзетулер қалпына келтірілді. Есептелген ұсынымдар қайта көрсетілді.", "Manual edits reset. Calculated recommendations restored."],
  requestTimeout: ["Сервис не ответил за 3 минуты. Проверьте его состояние перед повторным запросом.", "Сервис 3 минут ішінде жауап бермеді. Қайта сұраудан бұрын күйін тексеріңіз.", "The service did not respond within 3 minutes. Check its state before retrying."],
  stepData: ["Данные", "Деректер", "Data"], stepCalculate: ["Расчёт", "Есептеу", "Calculate"], stepRecommendations: ["Рекомендации", "Ұсынымдар", "Recommendations"], stepReview: ["Проверка", "Тексеру", "Review"], stepApprove: ["Подтверждение", "Бекіту", "Approve"], stepExport: ["Экспорт", "Экспорт", "Export"], workflow: ["Путь подготовки заказа", "Тапсырысты дайындау жолы", "Order preparation workflow"], runItems: ["ПОЗИЦИЙ В РАСЧЁТЕ", "ЕСЕПТЕГІ ПОЗИЦИЯЛАР", "ITEMS IN THIS RUN"],
  searchOrders: ["Поиск в рекомендациях", "Ұсынымдардан іздеу", "Search recommendations"], searchOrderHint: ["Артикул, товар или риск", "Артикул, тауар немесе тәуекел", "SKU, product or risk"], searchViewHelp: ["Поиск по таблице не меняет состав расчёта.", "Кестедегі іздеу есеп құрамын өзгертпейді.", "Table search does not change calculation scope."], viewTotal: ["СУММА ПОКАЗАННЫХ СТРОК", "КӨРСЕТІЛГЕН ЖОЛДАР СОМАСЫ", "VISIBLE ROWS TOTAL"],
  signalSpikes: ["SKU с исключёнными всплесками", "Шарықтаулары алынған SKU", "SKUs with spikes excluded"], signalStockout: ["SKU с восстановленным спросом", "Сұранысы қалпына келтірілген SKU", "SKUs with recovered demand"], signalMissing: ["SKU требуют проверки входов", "Кіріс деректерін тексеру қажет SKU", "SKUs needing input review"], signalsHelp: ["Факторы текущего расчёта", "Ағымдағы есеп факторлары", "Factors in this calculation"], coveredDays: ["Покрытие:", "Қамту:", "Coverage:"],
  dataEditor: ["Данные и параметры товаров", "Деректер және тауар параметрлері", "Data and product parameters"], dataEditorHelp: ["Проверка источников, корректировка остатков и сроков", "Дерек көздерін тексеру, қалдықтар мен мерзімдерді түзету", "Review sources, adjust stock and lead times"], template: ["Шаблон JSON ↓", "JSON үлгісі ↓", "JSON template ↓"], quality: ["ПРОВЕРЯЕМОСТЬ ИСХОДНЫХ ДАННЫХ", "БАСТАПҚЫ ДЕРЕКТЕРДІҢ ТЕКСЕРІЛУІ", "SOURCE DATA TRACEABILITY"], observed: ["Подтверждено источником", "Дерек көзімен расталған", "Observed in source"], assumed: ["Допущение", "Болжам", "Assumed"], missing: ["Не подтверждено", "Расталмаған", "Unconfirmed"], qualityHelp: ["Это полнота данных, а не точность прогноза. Неподтверждённые поля требуют проверки менеджером.", "Бұл — болжам дәлдігі емес, деректер толықтығы. Расталмаған өрістерді менеджер тексеруі керек.", "This describes data completeness, not forecast accuracy. A manager must review unconfirmed fields."],
  forecast_need: ["Прогнозная потребность", "Болжамды қажеттілік", "Forecast demand"], horizon_days: ["Горизонт, дней", "Есептеу кезеңі, күн", "Horizon, days"], review_days: ["Период пересмотра", "Қайта қарау кезеңі", "Review period"], safety_days: ["Страховой запас, дней", "Сақтандыру қоры, күн", "Safety coverage, days"], sku_growth: ["Рост артикула", "Артикул өсімі", "SKU growth"], category_growth: ["Рост категории", "Санат өсімі", "Category growth"], seasonality_indices: ["Коэффициенты сезонности", "Маусымдылық коэффициенттері", "Seasonality indices"], order_rounding: ["Округление заказа", "Тапсырысты дөңгелектеу", "Order rounding"], inbound_receipts: ["Ожидаемые поступления", "Күтілетін түсімдер", "Expected receipts"],
  report: ["Паспорт расчёта ↓", "Есеп паспорты ↓", "Decision report ↓"], reportSaved: ["Паспорт расчёта сохранён: исходные параметры, версия, результаты и статус проверки.", "Есеп паспорты сақталды: бастапқы параметрлер, нұсқа, нәтижелер және тексеру күйі.", "Decision report saved: inputs, version, results and review status."],
  close: ["Закрыть", "Жабу", "Close"], of: ["из", "ішінен", "of"], unit: ["ед.", "бірл.", "units"], fraction: ["доля", "үлес", "fraction"], noName: ["Без наименования", "Атауы жоқ", "Unnamed product"], noSupplier: ["Поставщик не указан", "Жеткізуші көрсетілмеген", "Supplier not specified"], noCategory: ["Без категории", "Санат жоқ", "No category"],
  noPolicies: ["В наборе нет категорий для настройки.", "Деректер жиынында баптайтын санаттар жоқ.", "This dataset has no categories to configure."], growthAdjustment: ["Поправка роста", "Өсім түзетуі", "Growth adjustment"], removePolicy: ["Удалить политику", "Саясатты жою", "Remove policy"],
  validation: ["Проверьте параметр и допустимый диапазон", "Параметр мен рұқсат етілген ауқымды тексеріңіз", "Check the parameter and allowed range"], policiesInvalid: ["Рост категории должен быть от −1 до 10, страховой запас — неотрицательным числом.", "Санат өсімі −1 мен 10 аралығында, сақтандыру қоры теріс емес сан болуы керек.", "Category growth must be between −1 and 10; safety stock must be non-negative."],
  demoLoading: ["Загружаем синтетический демонстрационный набор…", "Синтетикалық демо деректері жүктелуде…", "Loading the synthetic demonstration dataset…"], demoLoaded: ["Синтетические данные загружены. Запустите расчёт.", "Синтетикалық деректер жүктелді. Есептеуді бастаңыз.", "Synthetic data loaded. Run a calculation."], loading: ["Загружаем…", "Жүктелуде…", "Loading…"], uploadDone: ["Файлы приняты. Проверьте источник и параметры, затем выполните расчёт.", "Файлдар қабылданды. Дерек көзі мен параметрлерді тексеріп, есептеңіз.", "Files accepted. Review the source and parameters, then calculate."], refreshDone: ["Сервис доступен, источник обновлён.", "Сервис қолжетімді, дерек көзі жаңартылды.", "Service available; source refreshed."], requestError: ["Не удалось выполнить запрос. Проверьте сервис и повторите.", "Сұрау орындалмады. Сервисті тексеріп, қайталаңыз.", "Request failed. Check the service and try again."],
  noChart: ["История и прогноз для этой позиции не переданы сервисом.", "Бұл позицияның тарихы мен болжамы сервистен алынбады.", "History and forecast were not supplied for this item."], noBreakdown: ["Детальная разбивка не передана расчётным сервисом.", "Есептеу сервисі егжей-тегжейлі бөліністі бермеді.", "The calculation service did not provide a detailed breakdown."], noExplanation: ["Текстовое пояснение не передано сервисом.", "Сервис мәтіндік түсіндірме бермеді.", "The service did not provide a text explanation."], extraWarnings: ["Дополнительные предупреждения доступны в деталях позиций", "Қосымша ескертулер позиция мәліметтерінде қолжетімді", "More warnings are available in item details"], orderLines: ["строк к заказу", "тапсырыс жолы", "order lines"], filters: ["фильтры", "сүзгілер", "filters"], noFilters: ["без фильтров", "сүзгісіз", "no filters"],
  exportTitle: ["Экспорт текущего расчёта", "Ағымдағы есепті экспорттау", "Export current calculation"], approveBeforeExport: ["Утвердите изменения количества перед экспортом", "Экспортқа дейін мөлшер өзгерістерін бекітіңіз", "Approve quantity changes before export"], exported: ["Выгружено", "Экспортталды", "Exported"], categoryPrompt: ["Название категории из справочника:", "Анықтамалықтағы санат атауы:", "Category name from the product directory:"], existingPolicy: ["Политика этой категории уже отображается.", "Бұл санат саясаты көрсетілген.", "This category policy is already displayed."], changed: ["Параметры изменены. Выполните новый расчёт.", "Параметрлер өзгертілді. Қайта есептеңіз.", "Parameters changed. Run a new calculation."], invalidQuantity: ["Количество должно быть числом от 0 до 10¹².", "Мөлшер 0 мен 10¹² аралығындағы сан болуы керек.", "Quantity must be a number between 0 and 10¹²."], invalidProduct: ["Проверьте числовое значение: неотрицательное число, рост от −1.", "Санды тексеріңіз: теріс емес сан, өсім −1-ден бастап.", "Check the numeric value: non-negative, or growth from −1."],
  overview: ["Обзор", "Шолу", "Overview"], recommendations: ["Рекомендации", "Ұсынымдар", "Recommendations"], data: ["Данные", "Деректер", "Data"], settings: ["Параметры", "Параметрлер", "Settings"],
  workspace: ["РАБОЧАЯ ОБЛАСТЬ", "ЖҰМЫС АЙМАҒЫ", "WORKSPACE"], replenish: ["Пополнение склада", "Қойманы толықтыру", "Stock replenishment"], refresh: ["Обновить", "Жаңарту", "Refresh"],
  planning: ["РАБОЧЕЕ МЕСТО ЗАКУПЩИКА", "САТЫП АЛУ МЕНЕДЖЕРІНІҢ ЖҰМЫС ОРНЫ", "PURCHASING WORKSPACE"], title: ["Заказы на пополнение", "Толықтыру тапсырыстары", "Replenishment orders"],
  subtitle: ["Расчёт потребности по истории продаж, текущим остаткам и подтверждённым поставкам.", "Сату тарихы, ағымдағы қалдықтар және расталған жеткізілімдер негізінде қажеттілікті есептеу.", "Calculate demand from sales history, current stock and confirmed deliveries."],
  demo: ["▷ Загрузить демо", "▷ Демо жүктеу", "▷ Load demo"], upload: ["↑ Загрузить данные", "↑ Деректерді жүктеу", "↑ Upload data"], source: ["Источник данных", "Деректер көзі", "Data source"], choose: ["Выбрать файлы ↗", "Файлдарды таңдау ↗", "Choose files ↗"],
  noData: ["Данные ещё не загружены", "Деректер әлі жүктелмеген", "No data loaded yet"], synthetic: ["Синтетический демонстрационный набор", "Синтетикалық демо деректері", "Synthetic demonstration dataset"], loaded: ["Загруженные данные", "Жүктелген деректер", "Uploaded data"],
  inputs: ["ИСХОДНЫЕ ПАРАМЕТРЫ", "БАСТАПҚЫ ПАРАМЕТРЛЕР", "SOURCE PARAMETERS"], products: ["Товары и сроки поставки", "Тауарлар және жеткізу мерзімдері", "Products and lead times"],
  productsHelp: ["Остаток, срок, партию и рост можно скорректировать перед расчётом. Рост — доля (0,1 = +10%). Правки действуют до обновления страницы.", "Қалдықты, мерзімді, партияны және өсімді есептеуге дейін өзгертуге болады. Өсім — үлес (0,1 = +10%). Өзгерістер бет жаңартылғанша сақталады.", "Adjust stock, lead time, minimum order and growth before calculating. Growth is a fraction (0.1 = +10%). Edits last until page refresh."],
  search: ["Поиск SKU или товара", "SKU немесе тауарды іздеу", "Search SKU or product"], sku: ["АРТИКУЛ / ТОВАР", "АРТИКУЛ / ТАУАР", "SKU / PRODUCT"], supplierCategory: ["ПОСТАВЩИК / КАТЕГОРИЯ", "ЖЕТКІЗУШІ / САНАТ", "SUPPLIER / CATEGORY"], warehouse: ["СКЛАД", "ҚОЙМА", "WAREHOUSE"], stock: ["ОСТАТОК", "ҚАЛДЫҚ", "STOCK"], lead: ["СРОК, ДН.", "МЕРЗІМ, КҮН", "LEAD, DAYS"], moq: ["МИН. ПАРТИЯ", "МИН. ПАРТИЯ", "MIN. ORDER"], growth: ["РОСТ", "ӨСІМ", "GROWTH"],
  back: ["← Назад", "← Артқа", "← Previous"], next: ["Далее →", "Келесі →", "Next →"], category: ["КАТЕГОРИЯ", "САНАТ", "CATEGORY"], supplier: ["ПОСТАВЩИК", "ЖЕТКІЗУШІ", "SUPPLIER"], allWarehouses: ["Все склады", "Барлық қоймалар", "All warehouses"], allCategories: ["Все категории", "Барлық санаттар", "All categories"], allSuppliers: ["Все поставщики", "Барлық жеткізушілер", "All suppliers"],
  horizon: ["ГОРИЗОНТ ЗАКАЗА", "ТАПСЫРЫС КЕЗЕҢІ", "ORDER HORIZON"], days: ["дней", "күн", "days"], calculate: ["⟳ Рассчитать", "⟳ Есептеу", "⟳ Calculate"], recalculate: ["Пересчитать", "Қайта есептеу", "Recalculate"], limitations: ["Ограничения исходных данных и расчёта", "Деректер мен есептеу шектеулері", "Data and calculation limitations"],
  orderItems: ["ПОЗИЦИЙ К ПОПОЛНЕНИЮ", "ТОЛЫҚТЫРЫЛАТЫН ПОЗИЦИЯЛАР", "ITEMS TO REPLENISH"], suppliers: ["ПОСТАВЩИКИ", "ЖЕТКІЗУШІЛЕР", "SUPPLIERS"], draft: ["ЧЕРНОВИК ЗАКАЗА", "ТАПСЫРЫС ЖОБАСЫ", "DRAFT ORDER"], approved: ["УТВЕРЖДЁННЫЙ ЗАКАЗ", "БЕКІТІЛГЕН ТАПСЫРЫС", "APPROVED ORDER"], attention: ["ТРЕБУЮТ ВНИМАНИЯ", "НАЗАР АУДАРУ ҚАЖЕТ", "NEED ATTENTION"], inResult: ["В текущем результате", "Ағымдағы нәтижеде", "In current results"], criticalItems: ["Критические позиции в результате", "Нәтижедегі шұғыл позициялар", "Critical items in results"],
  amountHelp: ["Сумма по известным ценам; отсутствующие цены не равны нулю", "Белгілі бағалар бойынша сома; белгісіз баға нөлге тең емес", "Total from known prices; missing prices are not zero"], partialAmount: ["Неполная сумма", "Толық емес сома", "Partial amount"], noPrice: ["Цена неизвестна", "Баға белгісіз", "Price unknown"], unpriced: ["позиций без цены", "бағасы жоқ позиция", "items without prices"],
  sample: ["РАСЧЁТНАЯ ВЫБОРКА", "ЕСЕПТЕУ НӘТИЖЕСІ", "CALCULATION RESULTS"], orders: ["Рекомендации поставщикам", "Жеткізушілерге ұсынымдар", "Supplier recommendations"], approve: ["Утвердить заказ", "Тапсырысты бекіту", "Approve order"], calculating: ["Выполняем расчёт…", "Есептеу орындалуда…", "Calculating…"], notCalculated: ["Расчёт ещё не выполнен", "Есептеу әлі орындалмады", "Not calculated yet"],
  readyTitle: ["Данные готовы к расчёту", "Деректер есептеуге дайын", "Ready to calculate"], readyHelp: ["Проверьте параметры товаров и нажмите «Рассчитать».", "Тауар параметрлерін тексеріп, «Есептеу» түймесін басыңыз.", "Review product parameters and select Calculate."], emptyTitle: ["Сначала нужны исходные данные", "Алдымен бастапқы деректер қажет", "Start with source data"], emptyHelp: ["Загрузите файлы или откройте синтетический демонстрационный набор.", "Файлдарды жүктеңіз немесе синтетикалық демо деректерін ашыңыз.", "Upload files or open the synthetic demonstration dataset."], emptyFilters: ["По выбранным фильтрам строк нет", "Таңдалған сүзгілер бойынша жолдар жоқ", "No items match these filters"], changeFilters: ["Измените склад, категорию или поставщика и пересчитайте.", "Қойманы, санатты немесе жеткізушіні өзгертіп, қайта есептеңіз.", "Change warehouse, category or supplier and recalculate."],
  loadForCalc: ["Загрузите данные для расчёта", "Есептеу үшін деректерді жүктеңіз", "Load data to calculate"], runForFilters: ["Запустите расчёт для текущих фильтров", "Ағымдағы сүзгілер бойынша есептеңіз", "Calculate with current filters"], rows: ["позиций", "позиция", "items"], sales: ["записей продаж", "сату жазбасы", "sales records"], inbound: ["поставок в пути", "жолдағы жеткізілім", "inbound deliveries"], syntheticBadge: ["СИНТЕТИЧЕСКИЕ ДАННЫЕ", "СИНТЕТИКАЛЫҚ ДЕРЕКТЕР", "SYNTHETIC DATA"], noMatches: ["Совпадений не найдено. Измените поисковый запрос.", "Сәйкестік табылмады. Іздеу сұрауын өзгертіңіз.", "No matches. Change your search."],
  settingsTitle: ["Параметры расчёта", "Есептеу параметрлері", "Calculation settings"], settingsSubtitle: ["Настройки горизонта и политики категорий", "Кезең және санат саясаты параметрлері", "Horizon settings and category policies"], modelHelp: ["Это редактируемые параметры модели. Изменения попадут в следующий расчёт.", "Бұлар өзгертілетін модель параметрлері. Өзгерістер келесі есептеуге қолданылады.", "These are editable model parameters. Changes apply to the next calculation."], review: ["Период пересмотра заказа", "Тапсырысты қайта қарау кезеңі", "Order review period"], safety: ["Страховой запас по умолчанию", "Әдепкі сақтандыру қоры", "Default safety stock"], threshold: ["Порог единичного всплеска", "Бір реттік шарықтау шегі", "One-off spike threshold"], policies: ["Политики категорий", "Санаттар саясаты", "Category policies"], policiesHelp: ["Поправка к росту и страховому запасу.", "Өсім мен сақтандыру қорын түзету.", "Growth and safety-stock adjustments."], addCategory: ["＋ Добавить категорию", "＋ Санат қосу", "＋ Add category"], managerDecision: ["Решение о закупке всегда остаётся за менеджером.", "Сатып алу туралы шешімді әрқашан менеджер қабылдайды.", "The manager always makes the purchase decision."], recommendationOnly: ["Рекомендация ≠ размещённый заказ", "Ұсыным ≠ жіберілген тапсырыс", "Recommendation ≠ placed order"],
  approvalControl: ["КОНТРОЛЬ МЕНЕДЖЕРА", "МЕНЕДЖЕР БАҚЫЛАУЫ", "MANAGER REVIEW"], confirmDraft: ["Подтвердить черновик?", "Жобаны бекіту керек пе?", "Approve this draft?"], approvalWarning: ["Подтверждение сохраняет выбранные количества. Заказы автоматически не отправляются.", "Бекіту таңдалған мөлшерді сақтайды. Тапсырыстар автоматты түрде жіберілмейді.", "Approval saves selected quantities. Orders are not sent automatically."], reviewer: ["Имя ответственного менеджера", "Жауапты менеджердің аты", "Responsible manager's name"], namePlaceholder: ["Введите имя", "Атыңызды енгізіңіз", "Enter name"], returnReview: ["Вернуться к проверке", "Тексеруге оралу", "Back to review"], confirm: ["Подтвердить выбор", "Таңдауды бекіту", "Confirm selection"], saving: ["Фиксируем…", "Сақталуда…", "Saving…"],
  acknowledge: ["Я проверил ограничения: у части позиций не подтверждены остатки или сроки поставки. Принимаю ответственность за утверждение этих рекомендаций.", "Шектеулерді тексердім: кейбір позициялардың қалдығы немесе жеткізу мерзімі расталмаған. Осы ұсынымдарды бекіту жауапкершілігін қабылдаймын.", "I reviewed the limitations: some stock quantities or lead times are unconfirmed. I accept responsibility for approving these recommendations."], approvalScope: ["Будут утверждены все позиции текущего расчёта с выбранными количествами. Фильтр экспорта не изменяет состав утверждения.", "Ағымдағы есептің барлық позициялары таңдалған мөлшермен бекітіледі. Экспорт сүзгісі бекіту құрамын өзгертпейді.", "All items in this run will be approved with selected quantities. The export filter does not change approval scope."],
  critical: ["Критично", "Шұғыл", "Critical"], high: ["Высокий риск", "Жоғары тәуекел", "High risk"], normal: ["Планово", "Жоспарлы", "Planned"], covered: ["Покрыто", "Қамтылған", "Covered"], status: ["СТАТУС", "МӘРТЕБЕ", "STATUS"], orderQty: ["ЗАКАЗАТЬ", "ТАПСЫРЫС", "ORDER QTY"], amount: ["СУММА", "СОМА", "AMOUNT"], explanation: ["Пояснение", "Түсіндірме", "Explanation"], total: ["Итого", "Барлығы", "Total"], quantityHelp: ["Суммы пересчитываются при изменении количества", "Мөлшер өзгерсе, сома қайта есептеледі", "Amounts update when quantities change"],
  serviceReady: ["Сервис подключён", "Сервис қосылған", "Service connected"], serviceOffline: ["Сервис недоступен", "Сервис қолжетімсіз", "Service unavailable"], local: ["Локальное подключение", "Жергілікті қосылым", "Local connection"], calculationReady: ["Расчёт готов. Проверьте рекомендации перед подтверждением.", "Есеп дайын. Бекітуден бұрын ұсынымдарды тексеріңіз.", "Calculation ready. Review recommendations before approval."], approvedMessage: ["Рекомендации утверждены. Поставщикам ничего не отправлялось.", "Ұсынымдар бекітілді. Жеткізушілерге ештеңе жіберілген жоқ.", "Recommendations approved. Nothing was sent to suppliers."],
  light: ["Светлая тема", "Ашық тақырып", "Light theme"], dark: ["Тёмная тема", "Қараңғы тақырып", "Dark theme"], localeRecalculate: ["Язык интерфейса изменён. Пересчитайте для обновления пояснений сервера.", "Интерфейс тілі өзгерді. Сервер түсіндірмелерін жаңарту үшін қайта есептеңіз.", "Interface language changed. Recalculate to refresh server explanations."],
  explainTitle: ["ПОЯСНЕНИЕ РАСЧЁТА", "ЕСЕПТЕУ ТҮСІНДІРМЕСІ", "CALCULATION EXPLANATION"], dailyDemand: ["СРЕДНИЙ СПРОС / ДЕНЬ", "ОРТАША СҰРАНЫС / КҮН", "AVERAGE DEMAND / DAY"], coverage: ["ПОКРЫТИЕ", "ҚАМТУ", "COVERAGE"], excluded: ["ИСКЛЮЧЕНО ВСПЛЕСКОВ", "АЛЫП ТАСТАЛҒАН ШАРЫҚТАУЛАР", "EXCLUDED SPIKES"], demandChart: ["Спрос, единиц в день", "Сұраныс, күніне бірлік", "Demand, units per day"], history: ["История: среднее за месяц", "Тарих: айлық орташа", "History: monthly average"], forecast: ["Прогноз: по дням", "Болжам: күндер бойынша", "Forecast: daily"], logic: ["Логика рекомендации", "Ұсыным логикасы", "Recommendation logic"], excludedEvents: ["События, исключённые из базового спроса", "Базалық сұраныстан алынған оқиғалар", "Events excluded from baseline demand"], warnings: ["Ограничения и предупреждения", "Шектеулер мен ескертулер", "Limitations and warnings"],
};
const selectors = {
  ".sidebar-label": "workspace", '.nav-link[href="#overview"]': "overview", '.nav-link[href="#orders"]': "recommendations", '.nav-link[href="#data-workbench"]': "data", '.nav-link[href="#policies"]': "settings",
  ".sidebar-footnote": "managerDecision", ".breadcrumbs strong": "replenish", "#refresh-button": "refresh", ".hero-row .eyebrow": "planning", "#page-title": "title", ".hero-subtitle": "subtitle", "#demo-button": "demo", "#upload-button": "upload", "#source-title": "source", "#choose-file-button": "choose",
  ".products-head .field-label": "inputs", "#products-title": "products", ".products-head p": "productsHelp", ".product-table th:nth-child(1)": "sku", ".product-table th:nth-child(2)": "supplierCategory", ".product-table th:nth-child(3)": "warehouse", ".product-table th:nth-child(4)": "stock", ".product-table th:nth-child(5)": "lead", ".product-table th:nth-child(6)": "moq", ".product-table th:nth-child(7)": "growth", "#products-prev": "back", "#products-next": "next",
  'label[for="warehouse-filter"]': "warehouse", 'label[for="category-filter"]': "category", 'label[for="supplier-filter"]': "supplier", 'label[for="review-days"]': "horizon", "#settings-inline .number-with-unit span": "days", "#calculate-button": "calculate", ".warning-heading strong": "limitations",
  ".metric-card:nth-child(1) .metric-top span:first-child": "orderItems", ".metric-card:nth-child(2) .metric-top span:first-child": "suppliers", ".metric-card:nth-child(4) .metric-top span:first-child": "attention", ".metric-card:nth-child(2) .metric-foot": "inResult", ".metric-highlight .metric-foot": "amountHelp", ".metric-card:nth-child(4) .metric-foot": "criticalItems", "#orders .eyebrow": "sample", "#orders-title": "orders", "#approve-button": "approve",
  ".policy-summary-copy strong": "settingsTitle", ".policy-summary-copy small": "settingsSubtitle", ".policy-intro": "modelHelp", ".global-settings-grid .setting-field:nth-child(1) > span": "review", ".global-settings-grid .setting-field:nth-child(2) > span": "safety", ".global-settings-grid .setting-field:nth-child(3) > span": "threshold", ".category-policy-head strong": "policies", ".category-policy-head p": "policiesHelp", "#add-policy": "addCategory", ".policy-footer > span": "managerDecision", "#recalculate-settings": "recalculate", ".page-footer > span:last-child": "recommendationOnly",
  "#explain-dialog .eyebrow": "explainTitle", "#approval-dialog .eyebrow": "approvalControl", "#approval-dialog h2": "confirmDraft", "#approval-dialog p.approval-warning": "approvalWarning", ".reviewer-field > span": "reviewer", '.dialog-actions [data-close]': "returnReview", "#confirm-approval": "confirm",
};
const read = (key, fallback) => { try { return localStorage.getItem(key) || fallback; } catch { return fallback; } };
let locale = read("proofflow.locale", "ru");
if (!["ru", "kk", "en"].includes(locale)) locale = "ru";
let theme = read("proofflow.theme", "light");
if (!["light", "dark"].includes(theme)) theme = "light";
export const t = (key) => messages[key]?.[["ru", "kk", "en"].indexOf(locale)] ?? key;
const save = (key, value) => { try { localStorage.setItem(key, value); } catch { /* Privacy mode still permits in-memory preferences. */ } };
function setIcon(node, name, replace = false) {
  if (!node) return;
  if (replace) node.textContent = "";
  else node.querySelector(".ph-icon")?.remove();
  const icon = document.createElement("span");
  icon.className = "ph-icon";
  icon.setAttribute("aria-hidden", "true");
  icon.style.setProperty("--icon", `url('/static/assets/icons/${name}.svg')`);
  node.prepend(icon);
}
function apply() {
  document.documentElement.lang = locale;
  document.documentElement.dataset.theme = theme;
  document.title = `ProofFlow — ${t("replenish")}`;
  Object.entries(selectors).forEach(([selector, key]) => document.querySelectorAll(selector).forEach((node) => {
    if (node.classList.contains("nav-link")) {
      let label = node.querySelector(".nav-label");
      if (!label) { [...node.childNodes].filter(n => n.nodeType === 3).forEach(n => n.remove()); label = document.createElement("span"); label.className = "nav-label"; node.append(label); }
      label.textContent = t(key);
    } else node.textContent = t(key);
  }));
  document.querySelectorAll("[data-i18n]").forEach(node => { node.textContent = t(node.dataset.i18n); });
  document.querySelector("#product-search").placeholder = t("search");
  document.querySelector("#order-search").placeholder = t("searchOrderHint");
  document.querySelector("#reviewer-name").placeholder = t("namePlaceholder");
  document.querySelector('label[for="product-search"]').textContent = t("search");
  document.querySelector('label[for="export-supplier"]').textContent = t("exportTitle");
  document.querySelector("#export-supplier").setAttribute("aria-label", t("exportTitle"));
  document.querySelector("#refresh-button").title = t("refresh");
  document.querySelector(".sidebar").setAttribute("aria-label", t("workspace"));
  document.querySelector(".control-panel").setAttribute("aria-label", t("filters"));
  document.querySelector(".summary-grid").setAttribute("aria-label", t("overview"));
  document.querySelectorAll("[data-close]").forEach(node => node.setAttribute("aria-label", t("close")));
  document.querySelectorAll(".global-settings-grid .number-with-unit span").forEach(node => { if (node.textContent !== "×") node.textContent = t("days"); });
  document.querySelector("#decision-report").textContent = t("report");
  document.querySelector("#language-select").value = locale;
  const toggle = document.querySelector("#theme-toggle");
  toggle.textContent = theme === "dark" ? "☀" : "◐";
  toggle.title = t(theme === "dark" ? "light" : "dark");
  toggle.setAttribute("aria-label", toggle.title);
  toggle.setAttribute("aria-pressed", String(theme === "dark"));
  const icons = {
    '.nav-link[href="#overview"] .nav-icon': "squares-four-duotone",
    '.nav-link[href="#orders"] .nav-icon': "basket-duotone",
    '.nav-link[href="#data-workbench"] .nav-icon': "package-duotone",
    '.nav-link[href="#policies"] .nav-icon': "sliders-horizontal-duotone",
    '.source-icon': "package-duotone",
    '.metric-card:nth-child(1) .metric-symbol': "basket-duotone",
    '.metric-card:nth-child(2) .metric-symbol': "truck-duotone",
    '.metric-card:nth-child(3) .metric-symbol': "clipboard-text-duotone",
    '.metric-card:nth-child(4) .metric-symbol': "warning-circle-duotone",
    '#product-details .policy-summary-icon': "package-duotone",
    '#policy-details .policy-summary-icon': "sliders-horizontal-duotone",
  };
  Object.entries(icons).forEach(([selector, icon]) => document.querySelectorAll(selector).forEach(node => setIcon(node, icon, true)));
  const buttons = { '#refresh-button': "arrow-clockwise-regular", '#demo-button': "lightning-duotone", '#upload-button': "upload-simple-regular", '#calculate-button': "arrow-clockwise-regular", '#approve-button': "check-circle-regular", '#decision-report': "shield-check-duotone", '#export-csv': "file-csv-duotone", '#export-xlsx': "file-xls-duotone" };
  Object.entries(buttons).forEach(([selector, icon]) => {
    const node = document.querySelector(selector);
    [...node.childNodes].filter(child => child.nodeType === 3).forEach(child => { child.textContent = child.textContent.replace(/[▷↑⟳↓]/g, "").trim(); });
    setIcon(node, icon);
  });
  setIcon(toggle, theme === "dark" ? "sun-duotone" : "moon-duotone", true);
}
export const i18n = { t, apply, get locale() { return locale; }, setLocale(value) { if (["ru", "kk", "en"].includes(value)) { locale = value; save("proofflow.locale", locale); apply(); } }, toggleTheme() { theme = theme === "dark" ? "light" : "dark"; save("proofflow.theme", theme); apply(); } };
